import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jreleaser.model.Active

/*
 * ZIP-321 Kotlin Multiplatform library.
 *
 * K0 (v2): converted from a JVM-only `java-library` to `kotlin("multiplatform")`
 * with ZERO runtime dependencies. Production sources live in `commonMain` and
 * compile for every target (jvm + iOS).
 *
 * K1 (v2): the test suite moved from jvm-only kotest to `kotlin.test` in
 * `commonTest` so the same tests run on every target (jvm + iOS simulator).
 * Only the Jazzer fuzz harnesses remain in `jvmTest`. The shared conformance
 * corpus (test-vectors submodule) is embedded into `commonTest` sources at
 * build time by the `generateConformanceVectors` task below, which removes
 * all platform-specific resource/filesystem loading from the tests.
 *
 * NOTE: no `androidTarget()` in this PR. Android consumers use the `jvm`
 * variant (`org.zecdev:zip321-jvm`) meanwhile; a dedicated Android library
 * target is a follow-up.
 */

plugins {
    // Kotlin Multiplatform replaces the previous `org.jetbrains.kotlin.jvm`
    // + `java-library` combination.
    kotlin("multiplatform") version "2.0.20"
    id("org.jlleitschuh.gradle.ktlint") version "12.1.1"
    id("io.gitlab.arturbosch.detekt") version "1.23.7"

    `maven-publish`
    id("org.jreleaser") version "1.22.0"
    signing
}

repositories {
    mavenCentral()
}

val myGroupId = "org.zecdev"
val myVersion = project.property("LIBRARY_VERSION").toString()
group = myGroupId
version = myVersion

// ---------------------------------------------------------------------------
// Conformance corpus embedding (K1)
//
// The shared ZIP-321 vector corpus lives in the `test-vectors` git submodule
// as JSON files. `commonTest` runs on native targets that have neither a
// classloader nor a stable filesystem cwd, so instead of loading resources at
// runtime the task below embeds the raw JSON into a generated Kotlin source
// file (`GeneratedVectors.kt`) at build time. It also generates one
// `kotlin.test` function per corpus vector (`GeneratedZip321ConformanceTest.kt`)
// so per-vector granularity (names, counts, xfail reporting) is preserved on
// every target. Inputs/outputs are declared, so the sources regenerate
// whenever the submodule content changes.
// ---------------------------------------------------------------------------

val conformanceVectorsDir = rootProject.projectDir.resolve("test-vectors/vectors")

val generateConformanceVectors by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/conformance/kotlin")
    inputs.dir(conformanceVectorsDir)
    outputs.dir(outputDir)

    doLast {
        fun escapeForKotlin(text: String): String =
            buildString(text.length + 64) {
                for (ch in text) {
                    when (ch) {
                        '\\' -> append("\\\\")
                        '"' -> append("\\\"")
                        '$' -> append("\\$")
                        '\n' -> append("\\n")
                        '\r' -> append("\\r")
                        '\t' -> append("\\t")
                        else ->
                            if (ch.code < 0x20) {
                                append("\\u").append(ch.code.toString(16).padStart(4, '0'))
                            } else {
                                append(ch)
                            }
                    }
                }
            }

        val packageDir = outputDir.get().asFile.resolve("org/zecdev/zip321/conformance")
        packageDir.mkdirs()

        // Corpus JSON files, keyed by "<valid|invalid>/<file name>", in
        // deterministic name order.
        val jsonFiles =
            listOf("valid", "invalid").flatMap { dir ->
                conformanceVectorsDir.resolve(dir)
                    .listFiles { file -> file.name.endsWith(".json") }
                    .orEmpty()
                    .sortedBy { it.name }
                    .map { "$dir/${it.name}" to it }
            }
        check(jsonFiles.isNotEmpty()) {
            "No corpus JSON found under $conformanceVectorsDir. " +
                "Did you run `git submodule update --init`?"
        }

        packageDir.resolve("GeneratedVectors.kt").writeText(
            buildString {
                appendLine("// GENERATED by the `generateConformanceVectors` Gradle task — DO NOT EDIT.")
                appendLine("// Source of truth: test-vectors/vectors/**/*.json (git submodule).")
                appendLine("package org.zecdev.zip321.conformance")
                appendLine()
                appendLine("internal object GeneratedVectors {")
                appendLine("    val files: Map<String, String> = mapOf(")
                jsonFiles.forEachIndexed { i, (key, file) ->
                    val separator = if (i == jsonFiles.size - 1) "" else ","
                    appendLine("        \"$key\" to \"${escapeForKotlin(file.readText())}\"$separator")
                }
                appendLine("    )")
                appendLine("}")
            },
        )

        // One kotlin.test function per vector, mirroring the three phases of
        // the pre-K1 kotest runner. Render tests are only generated for
        // vectors that carry a canonical URI (currently all of them).
        val slurper = groovy.json.JsonSlurper()

        fun vectorsIn(dir: String): List<Map<*, *>> =
            jsonFiles
                .filter { (key, _) -> key.startsWith("$dir/") }
                .flatMap { (_, file) ->
                    @Suppress("UNCHECKED_CAST")
                    (slurper.parse(file) as List<Map<*, *>>)
                }
        val validVectors = vectorsIn("valid")
        val invalidVectors = vectorsIn("invalid")

        packageDir.resolve("GeneratedZip321ConformanceTest.kt").writeText(
            buildString {
                appendLine("// GENERATED by the `generateConformanceVectors` Gradle task — DO NOT EDIT.")
                appendLine("// One test per corpus vector; assertions live in ConformanceRunner.kt.")
                appendLine("package org.zecdev.zip321.conformance")
                appendLine()
                appendLine("import kotlin.test.Test")
                appendLine()
                appendLine("class GeneratedZip321ConformanceTest {")
                validVectors.forEach { vector ->
                    val name = vector["name"] as String
                    appendLine()
                    appendLine("    @Test")
                    appendLine("    fun `valid vector parses to the reference payments - $name`() {")
                    appendLine("        ConformanceRunner.checkValid(\"$name\")")
                    appendLine("    }")
                    if (vector["canonicalUri"] != null) {
                        appendLine()
                        appendLine("    @Test")
                        appendLine("    fun `valid vector re-renders to the reference canonical URI - $name`() {")
                        appendLine("        ConformanceRunner.checkRender(\"$name\")")
                        appendLine("    }")
                    }
                }
                invalidVectors.forEach { vector ->
                    val name = vector["name"] as String
                    appendLine()
                    appendLine("    @Test")
                    appendLine("    fun `invalid vector is rejected with a ZIP321 Errors - $name`() {")
                    appendLine("        ConformanceRunner.checkInvalid(\"$name\")")
                    appendLine("    }")
                }
                appendLine("}")
            },
        )
    }
}

kotlin {
    // JVM target keeps the toolchain the JVM-only build used.
    jvm {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_1_8)
        }
    }

    // iOS targets. Declaring iosArm64 + iosSimulatorArm64 alongside jvm makes
    // Kotlin's DEFAULT HIERARCHY TEMPLATE (applied automatically since 1.9.20)
    // materialise the intermediate `iosMain`/`iosTest` source sets, so a single
    // `src/iosTest` actual is shared by both iOS targets — no manual
    // `sourceSets` wiring or `applyDefaultHierarchyTemplate()` needed.
    iosArm64()
    iosSimulatorArm64()

    sourceSets {
        val commonMain by getting {
            // ZERO runtime dependencies. No kudzu, no guava, no commons-math3 —
            // and no crypto: the library performs no address validation, so it
            // needs no hash, no Bech32 and no Base58Check. Those live in
            // `commonTest` as reference checkers for the test suite only.
        }

        val commonTest by getting {
            // Embedded conformance corpus + generated per-vector tests (K1).
            kotlin.srcDir(generateConformanceVectors)
            dependencies {
                // kotlin.test replaces kotest so the suite runs on all targets.
                implementation(kotlin("test"))

                // ZIP-321 conformance corpus (TEST-ONLY): JSON tree parsing of
                // the embedded vectors. kotlinx-serialization-json is
                // multiplatform; only the JsonElement tree API is used (no
                // @Serializable classes), so the serialization compiler plugin
                // is intentionally NOT applied and production code gains no
                // new dependency.
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
            }
        }

        val jvmTest by getting {
            dependencies {
                // kotest was fully removed in K1 (nothing uses it anymore).
                // kotest-property returns with the property-based tests in a
                // later PR (see CHANGELOG).

                // Fuzzing (Jazzer + JUnit5 platform) stays JVM-only.
                implementation(platform("org.junit:junit-bom:5.11.4"))
                implementation("org.junit.jupiter:junit-jupiter")
                runtimeOnly("org.junit.platform:junit-platform-launcher")
                implementation("com.code-intelligence:jazzer-junit:0.24.0")
                implementation("com.code-intelligence:jazzer-api:0.24.0")
                runtimeOnly("com.code-intelligence:jazzer:0.24.0")
            }
        }
    }
}

dependencies {
    detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:1.23.3")
}

detekt {
    buildUponDefaultConfig = true
    allRules = false
    config.setFrom("$rootDir/tools/detekt.yml")
    autoCorrect = true
    // Grandfather the pre-existing findings (detekt was never gated in CI, which
    // runs only `test`). New code is still checked; regenerate with
    // `./gradlew :lib:detektBaseline` when intentionally changing baselined code.
    baseline = file("$rootDir/tools/detekt-baseline.xml")
    // KMP does not auto-wire detekt's default source set; point it at the
    // production Kotlin source directories explicitly.
    source.setFrom(
        "src/commonMain/kotlin",
        "src/jvmMain/kotlin",
        "src/iosMain/kotlin",
    )
}

tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach {
    exclude("**/test/**", "**/*Test*")
    reports {
        html.required.set(true)
        xml.required.set(true)
        txt.required.set(true)
        sarif.required.set(true)
        md.required.set(true)
    }
}

// All JVM test tasks (unit + fuzz regression) run on the JUnit 5 platform.
tasks.withType<Test>().configureEach {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}

// K1: iOS test linking/running is enabled (commonTest now has sources for all
// targets). Building/linking the iOS test binaries requires a full Xcode
// install; on machines where `xcode-select` points at the CommandLineTools,
// run Gradle with DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer.

// ---------------------------------------------------------------------------
// Publication
//
// BREAKING (v2): the KMP plugin publishes one Gradle-module publication plus
// one per target instead of the single JVM jar. Coordinates become:
//   org.zecdev:zip321                    (Gradle metadata; root module)
//   org.zecdev:zip321-jvm                (JVM artifact; Android consumes this)
//   org.zecdev:zip321-iosarm64
//   org.zecdev:zip321-iossimulatorarm64
// The base artifactId is remapped from the Gradle project name ("lib") to
// "zip321" to preserve the historical coordinate for the root/JVM modules.
// ---------------------------------------------------------------------------

// KMP publications need a javadoc jar for Maven Central validation; provide an
// (empty) stub so the publication model is complete and compiles.
val javadocJar by tasks.registering(Jar::class) {
    archiveClassifier.set("javadoc")
}

val myArtifactId = "zip321"
val isSnapshot = project.property("IS_SNAPSHOT").toString().toBoolean()
val myDescription = "A concise implementation of ZIP-321 in Kotlin."
val myRepoUrl = "https://github.com/zecdev/zcash-kotlin-payment-uri"

publishing {
    publications.withType<MavenPublication>().configureEach {
        // Remap "lib" / "lib-<target>" -> "zip321" / "zip321-<target>".
        artifactId = artifactId.replace("lib", myArtifactId)
        artifact(javadocJar)

        pom {
            name.set("Zcash Kotlin Payment URI")
            description.set(myDescription)
            url.set(myRepoUrl)
            inceptionYear.set("2023")
            scm {
                url.set(myRepoUrl)
                connection.set("scm:git:git://github.com/zecdev/zcash-kotlin-payment-uri.git")
                developerConnection.set("scm:git:ssh://git@github.com/zecdev/zcash-kotlin-payment-uri.git")
            }
            developers {
                developer {
                    id.set("ZecDev")
                    name.set("ZecDev")
                    url.set("https://github.com/zecdev")
                }
            }
            licenses {
                license {
                    name.set("The MIT License")
                    url.set("https://opensource.org/licenses/MIT")
                    distribution.set("repo")
                }
            }
        }
    }
    repositories {
        maven {
            url = layout.buildDirectory.dir("staging-deploy").get().asFile.toURI()
        }
    }
}

jreleaser {
    gitRootSearch.set(true)
    version = myVersion

    signing {
        active.set(Active.ALWAYS)
        armored.set(true)
    }

    deploy {
        active.set(Active.ALWAYS)
        maven {
            active.set(Active.ALWAYS)
            pomchecker {
                version.set("1.12.0")
                failOnWarning.set(false)
                failOnError.set(true)
            }
            project {
                description.set(myDescription)
                copyright.set("Copyright ZecDev.Org.")
                license.set("The MIT License.")
            }
            mavenCentral {
                active.set(Active.ALWAYS)
                create("maven-central") {
                    active.set(Active.ALWAYS)
                    url.set("https://central.sonatype.com/api/v1/publisher")
                    stagingRepository("build/staging-deploy")

                    // FIX: Jreleaser fails after attempt 61 but library is published anyway
                    maxRetries.set(180)
                    retryDelay.set(20)
                }
            }
        }
    }
}
