import org.jreleaser.model.Active
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "2.0.20"
    id("io.kotest") version "0.4.11"
    id("org.jlleitschuh.gradle.ktlint") version "12.1.1"
    id("io.gitlab.arturbosch.detekt") version "1.23.7"

    `maven-publish`
    id("org.jreleaser") version "1.22.0"
    signing
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use kotest
    testImplementation("io.kotest:kotest-runner-junit5:5.9.0")
    testImplementation("io.kotest:kotest-property:5.9.0")
    testImplementation("io.kotest:kotest-assertions-core-jvm:5.9.0")
    testImplementation("io.kotest:kotest-framework-engine-jvm:5.9.0")

    // Use Detekt
    detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:1.23.3")

    // parser
    implementation("io.github.copper-leaf:kudzu-core:5.1.0")
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:31.1-jre")

    // Fuzzing
    testImplementation(platform("org.junit:junit-bom:5.11.4"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("com.code-intelligence:jazzer-junit:0.24.0")

    // Jazzer
    testImplementation("com.code-intelligence:jazzer-junit:0.24.0") // JUnit glue
    testImplementation("com.code-intelligence:jazzer-api:0.24.0")   // <-- supplies FuzzedDataProvider
    testRuntimeOnly("com.code-intelligence:jazzer:0.24.0")          // native Jazzer engine

    // ZIP-321 conformance corpus (TEST-ONLY): JSON tree parsing of the shared
    // vectors in the `test-vectors` git submodule. Only the JsonElement tree
    // API is used (no @Serializable classes), so the kotlinx-serialization
    // compiler plugin is intentionally NOT applied and production code gains
    // no new dependency.
    testImplementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
}

// Expose the shared ZIP-321 conformance corpus (git submodule at the repo root)
// to the test runtime as classpath resources: valid/*.json and invalid/*.json.
sourceSets {
    test {
        resources {
            srcDir(rootProject.projectDir.resolve("test-vectors/vectors"))
        }
    }
}

detekt {
    buildUponDefaultConfig = true // preconfigure defaults
    allRules = false // activate all available (even unstable) rules.
    config.setFrom("$rootDir/tools/detekt.yml")
    autoCorrect = true
}

tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach {
    exclude("$rootDir/lib/src/test")
}

// Apply a specific Java toolchain to ease working on different environments.
java {

    withJavadocJar()
    withSourcesJar()
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach {
    reports {
        html.required.set(true) // observe findings in your browser with structure and code snippets
        xml.required.set(true) // checkstyle like format mainly for integrations like Jenkins
        txt.required.set(true) // similar to the console output, contains issue signature to manually edit baseline files
        sarif.required.set(true) // standardized SARIF format (https://sarifweb.azurewebsites.net/) to support integrations with GitHub Code Scanning
        md.required.set(true) // simple Markdown format
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}


val publicationVariant = "release"
val myVersion = project.property("LIBRARY_VERSION").toString()
val myArtifactId = "zip321"
val isSnapshot = project.property("IS_SNAPSHOT").toString().toBoolean()
val myDescription = "A concise implementation of ZIP-321 in Kotlin."
val myRepoUrl = "https://github.com/zecdev/zcash-kotlin-payment-uri"
val myGroupId = "org.zecdev"
jreleaser {
    gitRootSearch.set(true)
    version = myVersion

    signing {
        active.set(Active.ALWAYS)
        armored.set(true)
    }

    deploy {
        active.set(Active.ALWAYS)
        maven {
            active.set(Active.ALWAYS)
            pomchecker {
                version.set("1.12.0")
                failOnWarning.set(false)
                failOnError.set(true)
            }
            project {
                description.set("A concise implementation of ZIP-321 in Kotlin.")
                copyright.set("Copyright ZecDev.Org.")
                license.set("The MIT License.")
            }
            mavenCentral {
                active.set(Active.ALWAYS)
                create("maven-central") {
                    active.set(Active.ALWAYS)
                    url.set("https://central.sonatype.com/api/v1/publisher")
                    stagingRepository("build/staging-deploy")

                    // FIX: Jreleaser fails after attempt 61 but library is published anyway
                    maxRetries.set(180)
                    retryDelay.set(20)
                }
            }

        }
    }
}

publishing {
    publications {
        create<MavenPublication>("Maven") {
            from(components["java"])  // Publish the "java" component (the jar file)

            groupId = myGroupId
            artifactId = myArtifactId
            version = myVersion
            description = myDescription

            pom {
                artifactId = myArtifactId
                groupId = myGroupId
                name.set("Zcash Kotlin Payment URI")
                description.set(myDescription)
                url.set(myRepoUrl)
                inceptionYear.set("2023")
                scm {
                    url.set(myRepoUrl)
                    connection.set("scm:git:git://github.com/zecdev/zcash-kotlin-payment-uri.git")
                    developerConnection.set("scm:git:ssh://git@github.com/zecdev/zcash-kotlin-payment-uri.git")
                }
                developers {
                    developer {
                        id.set("ZecDev")
                        name.set("ZecDev")
                        url.set("https://github.com/zecdev")
                    }
                }
                licenses {
                    license {
                        name.set("The MIT License")
                        url.set("https://opensource.org/licenses/MIT")
                        distribution.set("repo")
                    }
                }
            }
        }
    }
    repositories {
        maven {
            url = layout.buildDirectory.dir("staging-deploy").get().asFile.toURI()
        }
    }
}
