/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.thecodebuffet.zcash.zip321

import Payment
import PaymentRequest
import RecipientAddress

/**
 * ZIP-321 object for handling formatting options.
 */
object ZIP321 {
    /**
     * Enumerates formatting options for URI strings.
     */
    sealed class FormattingOptions {
        /** Enumerates all payments. */
        object EnumerateAllPayments : FormattingOptions()

        /** Uses an empty parameter index. */
        data class UseEmptyParamIndex(val omitAddressLabel: Boolean) : FormattingOptions()
    }

    /**
     * Transforms a [PaymentRequest] into a ZIP-321 payment request [String].
     *
     * @param request The payment request.
     * @param formattingOptions The formatting options.
     * @return The ZIP-321 payment request [String].
     */
    fun uriString(
        from: PaymentRequest,
        formattingOptions: FormattingOptions = FormattingOptions.EnumerateAllPayments
    ): String {
        return when (formattingOptions) {
            is FormattingOptions.EnumerateAllPayments -> Render.request(from, 1u, false)
            is FormattingOptions.UseEmptyParamIndex -> Render.request(
                from,
                startIndex = null,
                omittingFirstAddressLabel = formattingOptions.omitAddressLabel
            )
        }
    }

    /**
     * Convenience function to generate a ZIP-321 payment URI for a single recipient with no amount.
     *
     * @param recipient A recipient address.
     * @param formattingOptions The formatting options.
     * @return The ZIP-321 payment URI [String].
     */
    fun request(
        recipient: RecipientAddress,
        formattingOptions: FormattingOptions = FormattingOptions.UseEmptyParamIndex(
            omitAddressLabel = true
        )
    ): String {
        return when (formattingOptions) {
            is FormattingOptions.UseEmptyParamIndex -> "zcash:".plus(
                Render.parameter(recipient, index = null, omittingAddressLabel = formattingOptions.omitAddressLabel)
            )
            else -> "zcash:".plus(Render.parameter(recipient, index = null, omittingAddressLabel = false))
        }
    }

    /**
     * Generates a ZIP-321 payment request [String] from a [Payment].
     *
     * @param payment The payment.
     * @param formattingOptions The formatting options.
     * @return The ZIP-321 payment request [String].
     */
    fun request(
        payment: Payment,
        formattingOptions: FormattingOptions = FormattingOptions.EnumerateAllPayments
    ): String {
        return uriString(PaymentRequest(payments = listOf(payment)), formattingOptions = formattingOptions)
    }
}
