/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.zecdev.zip321

import org.zecdev.zip321.model.Payment
import org.zecdev.zip321.model.PaymentRequest
import org.zecdev.zip321.model.RecipientAddress
import org.zecdev.zip321.parser.Parser

/**
 * ZIP-321 object for parsing and formatting Zcash payment request URIs.
 */
object ZIP321 {
    /**
     * The default maximum accepted input size for [parse].
     */
    const val DEFAULT_MAX_INPUT_BYTES: Int = 8 * 1024

    /**
     * The internal v1 error taxonomy raised by the throwing parse pipeline.
     *
     * This is an **internal** type in v2. The public error surface is the sealed [ZIP321Error]
     * taxonomy returned by [parse]; every case below is translated by [ZIP321Error.Companion.from].
     */
    internal sealed class Errors : Exception() {
        /**
         * There's a payment exceeding the max supply as [ZIP-321](https://zips.z.cash/zip-0321) forbids.
         */
        data class AmountExceededSupply(val value: UInt) : Errors()

        /**
         * There's a payment that is less than a decimal zatoshi as [ZIP-321](https://zips.z.cash/zip-0321) forbids.
         */
        data class AmountTooSmall(val value: UInt) : Errors()

        /**
         * Parsing encountered a duplicate [ZIP-321](https://zips.z.cash/zip-0321) URI parameter for the returned payment index.
         */
        data class DuplicateParameter(val parameter: String, val index: UInt?) : Errors()

        /**
         * An invalid address query parameter was found. paramIndex is provided in the associated value.
         */
        data class InvalidAddress(val index: UInt?) : Errors()

        /**
         * A memo field in the ZIP 321 URI was not properly base-64 encoded according to [ZIP-321](https://zips.z.cash/zip-0321)
         */
        object InvalidBase64 : Errors() {
            private fun readResolve(): Any = InvalidBase64
        }

        /**
         * not even a Zcash URI
         */
        object InvalidURI : Errors() {
            private fun readResolve(): Any = InvalidURI
        }

        /**
         * A memo value exceeded 512 bytes in length or could not be interpreted as a UTF-8 string
         * when using a valid UTF-8 lead byte
         */
        data class MemoBytesError(val error: Throwable, val index: UInt?) : Errors()

        /**
         * The [ZIP-321](https://zips.z.cash/zip-0321) request included more payments than can be created within a single Zcash transaction.
         * The associated value is the number of payments in the request.
         */
        data class TooManyPayments(val value: UInt) : Errors()

        /**
         * The payment at the associated value attempted to include a memo when sending to a transparent recipient address,
         * which is not supported by the [Zcash protocol](https://zips.z.cash/protocol/protocol.pdf).
         */
        data class TransparentMemoNotAllowed(val index: UInt?) : Errors()

        /**
         * The payment which index is included in the associated value did not include a recipient address.
         */
        data class RecipientMissing(val index: UInt?) : Errors()

        /**
         * The payment request includes a `paramIndex` that is invalid according to [ZIP-321](https://zips.z.cash/zip-0321) specs
         */
        data class InvalidParamIndex(val value: String) : Errors()

        /**
         * Some invalid value was found at a query parameter that a specific index
         */
        data class InvalidParamValue(val param: String, val index: UInt?) : Errors()

        /**
         * The [ZIP-321](https://zips.z.cash/zip-0321) URI was malformed and failed to parse.
         */
        data class ParseError(val value: String) : Errors()

        /**
         * A value was expected to be qchar-encoded but its decoding failed.
         * Associated type has the value that failed.
         */
        data class QcharDecodeFailed(val index: UInt?, val key: String, val value: String) : Errors()

        /**
         * The parser found a required parameter it does not recognize.
         * See [Forward compatibilty](https://zips.z.cash/zip-0321#forward-compatibility)
         */
        data class UnknownRequiredParameter(val value: String) : Errors()

        /**
         * the parser found a `paramname` with the wrong encoding
         */
        data class InvalidParamName(val paramName: String) : Errors()
    }

    /**
     * Selects the rendered form of a [PaymentRequest], reconciled with v2's paramindex
     * preservation.
     *
     * - [UseEmptyParamIndex] renders each payment at its ACTUAL stored `paramindex` (the empty
     *   paramindex — stored index `0` — renders with no `.n` suffix; index `5` renders
     *   `address.5=…`). When `omitAddressLabel` is `true` and the request holds exactly one
     *   payment at index `0`, the canonical single-payment leading-address form is emitted
     *   (`zcash:<addr>?amount=…`); otherwise the general `zcash:?address[.n]=…&…` form is used.
     *   This is the canonical reference form and the default for [uriString].
     * - [EnumerateAllPayments] is a NORMALIZATION mode: it discards the stored paramindices and
     *   re-numbers payments SEQUENTIALLY from `1` (`address.1=…&address.2=…`), always with
     *   explicit address labels under `zcash:?`. Use it to canonicalize a request onto a
     *   contiguous `1…n` index space.
     *
     * The empty request renders as the bare `zcash:` scheme in either mode.
     */
    sealed class FormattingOptions {
        /** Normalization mode: re-numbers all payments sequentially from `1`. */
        object EnumerateAllPayments : FormattingOptions()

        /** Canonical mode: preserves each payment's stored `paramindex` (index `0` is empty). */
        data class UseEmptyParamIndex(
            /**
             * Whether a single payment at index `0` renders as the leading-address form
             * `zcash:<addr>?…` instead of `zcash:?address=<addr>&…`.
             */
            val omitAddressLabel: Boolean,
        ) : FormattingOptions()
    }

    /**
     * Transforms a [PaymentRequest] into a ZIP-321 payment request [String].
     *
     * The default [formattingOptions] is the canonical reference form
     * ([FormattingOptions.UseEmptyParamIndex] with `omitAddressLabel = true`): a single payment at
     * the empty paramindex renders as `zcash:<addr>?amount=…`, and the round-trip law
     * `parse(uriString(from = r)) == success(r)` holds for every request `r`.
     *
     * @param from The payment request.
     * @param formattingOptions the rendered form; defaults to the canonical reference form.
     * @return The ZIP-321 payment request [String].
     */
    fun uriString(
        from: PaymentRequest,
        formattingOptions: FormattingOptions = FormattingOptions.UseEmptyParamIndex(omitAddressLabel = true),
    ): String {
        return Render.request(from, formattingOptions)
    }

    /**
     * Convenience function to generate a ZIP-321 payment URI for a single recipient with no amount.
     *
     * @param recipient A recipient address.
     * @param formattingOptions The formatting options.
     * @return a URI of the form `zcash:<recipient>` under the default (label-omitting) options,
     * `zcash:?address=<recipient>` under [FormattingOptions.UseEmptyParamIndex] without label
     * omission, or `zcash:?address.1=<recipient>` under
     * [FormattingOptions.EnumerateAllPayments].
     */
    fun request(
        recipient: RecipientAddress,
        formattingOptions: FormattingOptions =
            FormattingOptions.UseEmptyParamIndex(
                omitAddressLabel = true,
            ),
    ): String {
        return when (formattingOptions) {
            is FormattingOptions.UseEmptyParamIndex -> {
                val scheme = if (formattingOptions.omitAddressLabel) "zcash:" else "zcash:?"
                scheme.plus(
                    Render.parameter(
                        recipient,
                        index = null,
                        omittingAddressLabel = formattingOptions.omitAddressLabel,
                    ),
                )
            }
            else ->
                "zcash:?".plus(
                    Render.parameter(recipient, index = 1u, omittingAddressLabel = false),
                )
        }
    }

    /**
     * Renders a single-payment ZIP-321 request to a URI [String]. Defaults to the canonical
     * leading-address form (`zcash:<addr>?amount=…`).
     *
     * @param payment The payment.
     * @param formattingOptions the rendered form; defaults to the canonical reference form.
     * @return The ZIP-321 payment request [String].
     */
    fun request(
        payment: Payment,
        formattingOptions: FormattingOptions = FormattingOptions.UseEmptyParamIndex(omitAddressLabel = true),
    ): String {
        return uriString(PaymentRequest(payments = listOf(payment)), formattingOptions = formattingOptions)
    }

    /**
     * Parses a [ZIP-321](https://zips.z.cash/zip-0321) payment request from a URI [String].
     *
     * This is a **total** function: every input maps to a [Result], never a thrown error. Result
     * failures are ALWAYS [ZIP321Error].
     *
     * Input guards run FIRST, before any grammar work: input larger than [maxInputBytes] fails with
     * [ZIP321Error.InvalidURI]/[ZIP321Error.StaticReason.INPUT_TOO_LARGE]; the empty string fails
     * with [ZIP321Error.ParseError]/[ZIP321Error.StaticReason.EMPTY_INPUT]; a non-`zcash:` scheme
     * fails with [ZIP321Error.InvalidURI]/[ZIP321Error.StaticReason.NOT_ZCASH_SCHEME]; a `//`
     * authority component fails with [ZIP321Error.InvalidURI]/[ZIP321Error.StaticReason.INVALID_AUTHORITY].
     *
     * Both spellings of a single recipient — the leading-address form
     * `zcash:<addr>` and the labeled form `zcash:?address=<addr>` — parse to the SAME
     * [PaymentRequest]. Which of the two the URI used is a syntax choice and is not encoded in the
     * parsed model, matching the reference implementation.
     *
     * Recipient-address validation is fully DELEGATED: the library performs NO address validation
     * of its own, so an address is valid exactly when [validator] says so, and the
     * [AddressDescriptor] it returns is what drives the ZIP-321 payment rules (memo support,
     * zero-valued transparent outputs).
     *
     * @param uri the `zcash:` URI to parse.
     * @param expecting the consensus network this request is expected to be for. Every recipient
     * the [validator] accepts must report this network in its [AddressDescriptor], or the request
     * is rejected with [ZIP321Error.InvalidAddress].
     * @param validator the caller-supplied authority on recipient addresses. This is REQUIRED.
     * @param maxInputBytes the maximum accepted UTF-8 byte length of [uri].
     * @return [Result.success] with the parsed [PaymentRequest] or [Result.failure] with a
     * [ZIP321Error].
     */
    @Suppress("ReturnCount", "SwallowedException")
    fun parse(
        uri: String,
        expecting: Network,
        validator: AddressValidator,
        maxInputBytes: Int = DEFAULT_MAX_INPUT_BYTES,
    ): Result<PaymentRequest> {
        // Input guards run FIRST, before any grammar work.
        if (uri.encodeToByteArray().size > maxInputBytes) {
            return Result.failure(ZIP321Error.InvalidURI(ZIP321Error.StaticReason.INPUT_TOO_LARGE))
        }
        if (uri.isEmpty()) {
            // The corpus classifies the empty string (no `zcash:` prefix to even begin parsing) as
            // parseError.
            return Result.failure(ZIP321Error.ParseError(ZIP321Error.StaticReason.EMPTY_INPUT))
        }
        if (!uri.startsWith("zcash:")) {
            return Result.failure(ZIP321Error.InvalidURI(ZIP321Error.StaticReason.NOT_ZCASH_SCHEME))
        }
        // A `//` authority component is forbidden by ZIP-321's top-level grammar.
        if (uri.substring("zcash:".length).startsWith("//")) {
            return Result.failure(ZIP321Error.InvalidURI(ZIP321Error.StaticReason.INVALID_AUTHORITY))
        }

        return try {
            Result.success(Parser(expecting, validator).parse(uri))
        } catch (error: ZIP321Error) {
            // Raised directly by `Payment`/`PaymentRequest` construction.
            Result.failure(error)
        } catch (error: Errors) {
            Result.failure(ZIP321Error.from(error))
        } catch (error: IllegalArgumentException) {
            Result.failure(ZIP321Error.ParseError(ZIP321Error.StaticReason.MALFORMED_URI))
        }
    }
}
